services:
  pythonapp:
    build: ./
    command: sh -c "sleep 10s ; pytest ./test_connect_mysql.py"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'stylish_backend'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'